version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build:
    docker:
      - image: "cimg/node:18.17"  
    steps:
      - checkout
      - run:
          name: Check Node & NPM Versions Before Install
          command: |
            node -v
            npm -v
      - run:
          name: Manually Install a Stable NPM Version
          command: |
            npm install -g npm@10  # Use a known stable version (e.g., NPM 10)
            npm -v  # Verify after installation
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build